name: Main workflow

on:
  pull_request:
  push:
  schedule:
    - cron: '5 14 * * *'

jobs:
  check-version-numbers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check version numbers
        run: ./version.sh
  
  package-python:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upgrade pip and build
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade build

      - name: Build wheel
        run: python3 -m build
            
      - name: Upload binary wheel
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist/*.whl
      
  deploy:
    needs:
      - check-version-numbers
      - package-python
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
      
    steps:
      - name: Download distributions
        uses: actions/download-artifact@v2

      - name: Deploy test distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          verbose: true
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true            
              
      - name: Deploy tagged release on PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
