name: Test
on: 
  pull_request_target:
    types: [assigned, opened, synchronize, reopened, ready_for_review]
    paths: 
        - shasta/**
  push:
    branches:
      - main
      - future
    paths: 
      - libdash/**
      - shasta/**
jobs:
  Shasta-Test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu 20.04
    runs-on: ${{ matrix.os }}
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v2 
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Running Tests
        run: |
          pip install .

          cd tests;
          make test
          test_succ=$?

          timer="$(LANG=en_us_88591; date)"
          echo "VERSION<<EOF" >> "$GITHUB_ENV"
          echo "OS:${{matrix.os}}" >> "$GITHUB_ENV"
          echo "$timer" >> "$GITHUB_ENV"
          cat python.log >> "$GITHUB_ENV"
          echo 'EOF' >> "$GITHUB_ENV"

          exit $test_succ
